version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: php:8.2-fpm
    container_name: laravel
    working_dir: /var/www
    volumes:
      - /projekty/projekt1/backend:/var/www
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
    ports:
      - "8001:8000"
    command: ["sh", "-c", "composer install && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"]

  frontend:
    image: node:18
    container_name: vue
    working_dir: /app
    volumes:
      - /projekty/projekt1/frontend:/app
    ports:
      - "5173:5173"
    command: ["sh", "-c", "npm install && npm run dev"]

volumes:
  mysql_data:
